### ISSUE TITLE
node-gyp build error on ubuntu due to bignum install fail 

### ISSUE THREAD

**Issue by parinaA** [bitpay/node-bitpay-client#104]
On running
```
npm install bitpay --save
```
I get as error in node-gyp build failed due to bignum@0.13.0 install fail as attached in the error log.
```
npm ERR! bignum@0.13.0 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bignum@0.13.0 install script.
```
node : v 12.13.0
ubuntu : v 19.04
npm: v 6.12.0
python: v 2.7.16
[2019-10-28T09_43_29_252Z-debug.log](https://github.com/bitpay/node-bitpay-client/files/3778063/2019-10-28T09_43_29_252Z-debug.log)

**Comment by thejoshualewis** [comment]
Hi @parinaA 
Try installing bignum separately
` npm install --save bignum`
