### ISSUE TITLE
Bitcoin address not available, try again later

### ISSUE THREAD

**Issue by vmatekole** [bitpay/node-bitpay-client#82]
I am using this module within MeteorJS, deployed in Docker. I have created a key pair and generated config. Copied the latter to the home dir of my Docker image and have also enforced config on the client 

```
client = bitpay.createClient privKey, {
      config: {
        apiHost: 'bitpay.com',
        apiPort: 443,
        forceSSL: true
      }
    }
```
I consistently get a response -  error: 'Bitcoin address not available, try again later' } when attempting to create invoices. When I try with the cli, there is no issue.

**Comment by vmatekole** [comment]
I resolved this issue... Unfortunately, the error message is misleading... The root cause was sending a string as opposed to an integer in the create invoice request.

**Comment by SilverFire** [comment]
For me the reason was sum equals zero.
