### ISSUE TITLE
Bitpay-rest Payout Example Posting Failing

### ISSUE THREAD

**Issue by Undeadkillz** [bitpay/node-bitpay-client#91]
Hello,
I am trying to use the Payout API, however, it seems that it keeps failing, I am not sure if this is a node-BitPay issue or not, but the example posted also fails. Is the API restricted to certain people, or is the example not up-to-date?

Regards,
Samer

**Comment by unusualbob** [comment]
Hi,

Yes, the payouts APIs are restricted, reach out to the sales team to get your account enabled.
